$:
  push:
    - docker:
        image: maven:3.8.6-openjdk-8
        volumes:
          - /root/.m2:copy-on-write
      imports:
        - https://cnb.cool/iceolive/private-config/-/blob/main/smtp.yml
        - https://cnb.cool/iceolive/private-config/-/blob/main/ossrh.yml
      stages:
        - mvn clean deploy -s ./settings.xml
        - name: notify
          image: drillster/drone-email
          settings:
            host: $smtp_host
            username: $smtp_username
            password: $smtp_password
            from: $smtp_from
            recipients: $smtp_recipients
            subject: 成功发布${CNB_REPO_NAME_LOWERCASE}@${CNB_BRANCH}
            body: 成功发布${CNB_REPO_NAME_LOWERCASE}@${CNB_BRANCH}
      failStages:
        - name: notify
          image: drillster/drone-email
          settings:
            host: $smtp_host
            username: $smtp_username
            password: $smtp_password
            from: $smtp_from
            recipients: $smtp_recipients
            subject: 发布${CNB_REPO_NAME_LOWERCASE}@${CNB_BRANCH}失败
            body: 发布${CNB_REPO_NAME_LOWERCASE}@${CNB_BRANCH}失败